#!/bin/sh
PKG_NAME=natter
[ -x "$(command -v nft)" ] && FW='fw4' || FW='fw3'

if [ ! -f /etc/${PKG_NAME}/custom-script.sh ]; then
	mkdir -p /etc/${PKG_NAME} 2>/dev/null
	cat <<-EOF > /etc/${PKG_NAME}/custom-script.sh
	#!/bin/sh
	#
	EOF
fi
chmod 755 /etc/${PKG_NAME}/custom-script.sh

uci show firewall | grep -E "firewall.@rule\[.+\.name='NatTypeTest'" >/dev/null
if [ "$?" == "1" ]; then
	. /lib/functions/network.sh
	network_find_wan wan_iface
	for ext_iface in $wan_iface; do
		network_get_device ext_device $ext_iface
		srczone=$($FW -q device "$ext_device")
	done
	section=$(uci add firewall rule)
	uci -q batch <<-EOF >/dev/null
		set firewall.$section.name='NatTypeTest'
		set firewall.$section.src="$srczone"
		set firewall.$section.dest_port='3456'
		set firewall.$section.target='ACCEPT'
		commit firewall
	EOF
fi
uci show luci | grep "name='Test Natter'" >/dev/null
if [ "$?" == "1" ]; then
	section=$(uci add luci command)
	uci -q batch <<-EOF >/dev/null
		set luci.$section.name='Test Natter'
		set luci.$section.command='natter --check-nat 3456'
		commit luci
	EOF
fi
