#!/bin/sh
PKG_NAME=natter
[ -x "$(command -v nft)" ] && FW='fw4' || FW='fw3'

white_script() {
	cat <<-EOF > /etc/${PKG_NAME}/custom-script.sh
	#!/bin/sh
	#
	EOF
	sed -n '1,/^echo /{s|^echo .*|# Write your upload script below...|;p}' /usr/share/${PKG_NAME}/natter-hook.sh >> /etc/${PKG_NAME}/custom-script.sh
}
if [ ! -f /etc/${PKG_NAME}/custom-script.sh ]; then
	mkdir -p /etc/${PKG_NAME} 2>/dev/null
	white_script
else
	mv -f /etc/${PKG_NAME}/custom-script.sh /etc/${PKG_NAME}/custom-script.sh.bak
	sed -Ei "1,/^#+ Write your upload script below.../{s|^|#|g}" /etc/${PKG_NAME}/custom-script.sh.bak
	white_script
	cat /etc/${PKG_NAME}/custom-script.sh.bak >> /etc/${PKG_NAME}/custom-script.sh
fi
chmod 755 /etc/${PKG_NAME}/custom-script.sh
uci show firewall | grep -E "firewall.@rule\[.+\.name='NatTypeTest'" >/dev/null
if [ "$?" == "1" ]; then
	. /lib/functions/network.sh
	network_find_wan wan_iface
	for ext_iface in $wan_iface; do
		network_get_device ext_device $ext_iface
		srczone=$($FW -q device "$ext_device")
	done
	section=$(uci add firewall rule)
	uci -q batch <<-EOF >/dev/null
		set firewall.$section.name='NatTypeTest'
		set firewall.$section.src="$srczone"
		set firewall.$section.dest_port='3456'
		set firewall.$section.target='ACCEPT'
		commit firewall
	EOF
fi
uci show luci | grep "name='Test Natter'" >/dev/null
if [ "$?" == "1" ]; then
	section=$(uci add luci command)
	uci -q batch <<-EOF >/dev/null
		set luci.$section.name='Test Natter'
		set luci.$section.command='natter --check-nat 3456'
		commit luci
	EOF
fi
uci -q batch <<-EOF
	delete firewall.${PKG_NAME}
	set firewall.${PKG_NAME}=include
	set firewall.${PKG_NAME}.type=script
	set firewall.${PKG_NAME}.path=/usr/share/${PKG_NAME}/$FW.include
	commit firewall
EOF
if [ "$FW" == "fw3" ]; then
uci -q batch <<-EOF
	set firewall.${PKG_NAME}.family=any
	set firewall.${PKG_NAME}.reload=1
	commit firewall
EOF
fi
